use_frameworks!

platform :ios, '8.0'

target 'HSKit_Example' do
  pod 'HSKit', :path => '../'

  target 'HSKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
